version: '3.8'

services:
  django_app:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    depends_on:
      - sql_server
    networks:
      - expense_net

  sql_server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server
    environment:
      SA_PASSWORD: "haroon111??M"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - expense_net

networks:
  expense_net:
